# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6eaf9040be0c7a4a181dcf194829d02677292723fc0d107867bf19fe011c345c0008612c6ef3c0674bb38c123ee1906c4048129c526c6f2dcb1828ee7b2692

test:
  secret_key_base: 50e14f04af927051a48be15812b3240955f2085a31b7b1afbbe8ad8548d62bb3cdd0145cfeb5c6ebb99d1168a6b62b9b2202dba02e8368c6888d57b518d535b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
